spring:
  application:
    name: zxgk
  datasource:
    url: jdbc:mysql://localhost:3306/zxgk?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 23456789
logging:
  level.com.f.zxgk: debug
server:
  port: 9001
